//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.10 at 12:41:34 PM IST 
//


package org.stackspace.spark.config.web;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.stackspace.spark.config.web package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SparkConfig_QNAME = new QName("http://stackspace.org/spark/config/web", "spark-config");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.stackspace.spark.config.web
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SparkConfig }
     * 
     */
    public SparkConfig createSparkConfig() {
        return new SparkConfig();
    }

    /**
     * Create an instance of {@link CommandMappings }
     * 
     */
    public CommandMappings createCommandMappings() {
        return new CommandMappings();
    }

    /**
     * Create an instance of {@link CommandMapping }
     * 
     */
    public CommandMapping createCommandMapping() {
        return new CommandMapping();
    }

    /**
     * Create an instance of {@link Forward }
     * 
     */
    public Forward createForward() {
        return new Forward();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SparkConfig }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://stackspace.org/spark/config/web", name = "spark-config")
    public JAXBElement<SparkConfig> createSparkConfig(SparkConfig value) {
        return new JAXBElement<SparkConfig>(_SparkConfig_QNAME, SparkConfig.class, null, value);
    }

}
