//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.10 at 12:41:34 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://stackspace.org/spark/config/web", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.stackspace.spark.config.web;
