//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.10 at 12:41:34 PM IST 
//


package org.stackspace.spark.config.web;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for spark-config complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="spark-config">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="command-mappings" type="{http://stackspace.org/spark/config/web}command-mappings" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "spark-config", propOrder = {
    "commandMappings"
})
public class SparkConfig {

    @XmlElement(name = "command-mappings")
    protected CommandMappings commandMappings;

    /**
     * Gets the value of the commandMappings property.
     * 
     * @return
     *     possible object is
     *     {@link CommandMappings }
     *     
     */
    public CommandMappings getCommandMappings() {
        return commandMappings;
    }

    /**
     * Sets the value of the commandMappings property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommandMappings }
     *     
     */
    public void setCommandMappings(CommandMappings value) {
        this.commandMappings = value;
    }

}
